exports.Names  =[
    "Abebe", "Abeja", "Abigail", "Abiy", "Adanech", "Adem", "Addis", "Adugna", "Aelaf", "Afenig",
    "Afsar", "Aidan", "Aikant", "Aisha", "Almaz", "Amar", "Amin", "Amir", "Amir", "Anania",
    "Andinet", "Angeth", "Anhar", "Anwar", "Aregash", "Ariel", "Asher", "Ashtyn", "Aster", 
    "Asrat", "Assefa", "Bafele", "Balech", "Baker", "Belay", "Bila", "Biruk", "Biru", "Buna",
    "Buzar", "Cecilia", "Chaltu", "Chenda", "Dagna", "Dawit", "Debela", "Debre", "Dema", 
    "Denish", "Desalegn", "Desta", "Dewit", "Dewit", "Eden", "Elias", "Elias", "Elias", 
    "Elsa", "Enoch", "Enyew", "Ermias", "Eshetu", "Eyob", "Fikirte", "Fikru", "Fisseha", 
    "Gabriel", "Gadi", "Gashaw", "Genet", "Getachew", "Gideon", "Girum", "Gizachew", 
    "Gizaw", "Hana", "Hana", "Hailu", "Hanna", "Hanna", "Hawi", "Heber", "Hedija", 
    "Hewan", "Hiruy", "Hope", "Idris", "Imran", "Jemal", "Jemila", "Jemal", "Jonas", 
    "Joseph", "Julius", "Kassahun", "Kebede", "Kenya", "Kidane", "Kirsten", "Kiflu", 
    "Kinfe", "Kirk", "Kurt", "Lemlem", "Lidya", "Lulu", "Maia", "Malaka", "Malet", 
    "Mamo", "Marion", "Masresha", "Meron", "Mesfin", "Meskerem", "Meskerem", "Mulu", 
    "Muluken", "Mulugeta", "Nardos", "Nega", "Nega", "Netsanet", "Neway", "Nimro", 
    "Nunu", "Obed", "Omer", "Ruth", "Rahel", "Sabrina", "Samrawit", "Samuel", "Sara", 
    "Selam", "Selamawit", "Senait", "Serkalem", "Seyfu", "Shahi", "Shewan", "Simegnew", 
    "Simret", "Sirak", "Sirak", "Solomon", "Soni", "Sosina", "Tadele", "Tadla", 
    "Tafese", "Takle", "Tamara", "Tana", "Tanzina", "Teferi", "Tesfaye", "Tewodros", 
    "Tirhas", "Tsedal", "Tsion", "Tsion", "Tsinat", "Tsega", "Wale", "Wenner", 
    "Wondimu", "Yared", "Yemane", "Yilma", "Zemenu", "Zehay", "Zeyda", "Zewdie", 
    "Zeyla", "Abebe", "Biruk", "Amanuel", "Yohannes", "Zemelak", "Biniam", 
    "Eyob", "Hikmat", "Amara", "Simeon", "Shere", "Nebiyou", "Ethiopia", "Enkhta", 
    "Esther", "Henok", "Daniel", "Girma", "Meles", "Weyni", "Martha", "Abel", 
    "Mesfin", "Isaiah", "Miriam", "Baraka", "Alfred", "Kikuno", "Ruth", "Nardos", 
    "Asha", "Sofiya", "Seif", "Andreas", "Adamu", "Moges", "Menkre", "Meraf", 
    "Meheret", "Sengal", "Gizu", "Tinsae", "Halima", "Lemlem", "Tafara", "Giddo", 
    "Fela", "Nihal", "Liya", "Brigette", "Mariana", "Winta", "Samira", "Walda", 
    "Saro", "Yihun", "Mamo", "Azmari", "Ghebre", "Mireya", "Yeabsera", "Semhal", 
    "Sharay", "Adane", "Jara", "Hiyab", "Yergalem", "Wondwossen", "Nihal", 
    "Fana", "Selamawit", "Anya", "Barack", "Hannah", "Tena", "Bacha", "Dawne", 
    "Mola", "Meklit", "Nida", "Tsige", "Lelise", "Rita", "Khadra", "Winta"
]
